### ISSUE TITLE
How to trigger new saved post?

### ISSUE THREAD

**Issue by Hans-Maulwurf** [jcostello93/node-red-contrib-node-reddit#53]
Hey guys,

is it possible with this node to trigger when I hit "save" on a reddit post or comment? I want to do something like
* click on save on reddit
* send an emal with the content of this post or the whole thread
* unsave the item after like 1 week

Is this somehow possible? Thanks for your help :)

**Comment by jcostello93** [comment]
Hi Hans, 

I added an option (v 1.0.7) in the get node to allow you get saved, upvoted, downvoted, hidden, or gilded content. 

You can try scheduling an inject node to periodically check your saved content. There is a way to do this with the stream node too, but it would require an additional step other than just saving the content. 

The react node can unsave the item.

**Comment by jcostello93** [comment]
Closing since we added this feature.
