### ISSUE TITLE
Feedparser to Reddit issues

### ISSUE THREAD

**Issue by Valaia** [jcostello93/node-red-contrib-node-reddit#62]
Hi there! I am trying to create a flow that uses feedparser and posts new items to a subreddit. I am using the Create Reddit node for this. For the title I use {{{article.title}}} and in the Text box I use {{{payload}}} to post the full article. The triple { works well for the title and converts HTML, but the body still remains in HTML. Any ideas as to why this is happening? Thank you so much for the node and for your attention!

**Comment by jcostello93** [comment]
The node-reddit nodes use mustache syntax to dynamically access the properties of an incoming msg, but they don't escape the HTML like the template node would. 

I tested the feedparse node today and it seems like msg.article.title is always a string with no HTML. You can try stripping the HTML tags from msg.payload (using regex) and then posting the resulting string to Reddit. 

I tried the function from this article and it seemed to work fine: 

https://www.w3resource.com/javascript-exercises/javascript-string-exercise-35.php

Let me know how it goes!

**Comment by ljmerza** [comment]
this doesn't work for url paths. Mustache escapes everything by default so passing a complex url is destroyed by mustache. The line that parses the input really needs to be `Mustache.render(unescape(source),view)`

**Comment by jcostello93** [comment]
Fixed in https://github.com/jcostello93/node-red-contrib-node-reddit/pull/63
