### ISSUE TITLE
Reddit to Pushover for mobile post notifications help?

### ISSUE THREAD

**Issue by Turbo123T3** [jcostello93/node-red-contrib-node-reddit#68]
Hello, I'm setting up a Node-RED flow for my HASSIO to notify me of new Reddit posts through my mobile devices due to the current IFTTT situation. I have it all setup and have got (node-red-contrib-node-reddit) & (node-red-contrib-pushover) connected and working almost flawlessly, the only flaw is that the format that Pushover shows is very very raw and was wondering if anyone knew a better way to format the two together by any chance?

FLOW:
Reddit - Pushover 
https://community-assets.home-assistant.io/original/3X/4/5/45ae82cc88f4d31e0103fac1090de51886f7492d.png

So, it works... It just looks like this on my mobile devices.

https://drive.google.com/file/d/1J23DS6_uqGRlfUSxj4AppODzw1-C3-9w/view?usp=sharing

Ideally I think it would be nice to have the Pushover notification of the Reddit post look like: [Title] [Subject] instead of this large wall. Any help is appreciated!

**Comment by jcostello93** [comment]
Cool idea!

In this case, msg.payload is a JSON object and it looks like pushover is stringify-ing it. 

Perhaps put a function node in between them and set msg.payload to a string. I think this would work:

```
msg.payload = msg.payload.title;

return msg;
```

**Comment by Turbo123T3** [comment]
Hey, Thanks! That does work in fact! thanks a bunch.

_I was messing around with the change function as well and if you set msg.payload to msg.payload.title that works too, my next mission is to get the msg.payload.title & msg.payload.permalink together in a single function, and then add https://www.reddit.com in front of the permalink for easy copy/paste and then optimal messages for deals.

Any advice for that? :)_

EDIT:

Alright, I have gotten this even better than I ever thought it could be thanks to jcostello93 from the node-red-contrib-node-reddit project and TheWAPMop from the discord.

[{"id":"c25a0d1.83aa5f","type":"tab","label":"Reddit Nodes","disabled":false,"info":""},{"id":"d50336cd.9b6608","type":"stream","z":"c25a0d1.83aa5f","name":"","reddit":"","kind":"submissions","subreddit":"GameDeals","filter":"inbox","markedAsRead":false,"timeout":"","pollTime":"","x":130,"y":160,"wires":[["4db71c66.73c5d4"]]},{"id":"4db71c66.73c5d4","type":"function","z":"c25a0d1.83aa5f","name":"","func":"msg.payload = msg.payload.title + \" https://www.reddit.com\" + msg.payload.permalink;\n\nreturn msg;","outputs":1,"noerr":0,"initialize":"","finalize":"","x":320,"y":160,"wires":[["c343b449.7d9d78"]]},{"id":"c343b449.7d9d78","type":"pushover","z":"c25a0d1.83aa5f","name":"","device":"","title":"New Post: r/GameDeals","priority":0,"sound":"cashregister","url":"","url_title":"","html":false,"x":550,"y":160,"wires":[]}]

is the flow.

For anyone reading this I recommend setting these up for maximum savings
r/GameDeals
r/BuildAPCSales
r/ConsoleDeals
r/FREE
r/FreeEBOOKS
r/giveaways
r/NintendoSwitchDeals
r/FreeGamesOnSteam
r/GunDeals

**Comment by jcostello93** [comment]
Glad it worked! 😄
